### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by halvardssm** [fdionisi/deno-argon2#4]
OS: MacOS Catalina
Deno version: 1.9.2
Argon version: 0.9.2

Hi @fdionisi ! I am trying to use the argon library in an API which I am making, but I am getting this error:

```shell
error: Uncaught (in promise) TypeError: invalid promise id: expected type `rusty_v8::data::Integer`, got `rusty_v8::data::Value`
      let result = Deno.core.dispatch(argon2_hash, args, buf)!;
                             ^
    at Object.hash (https://deno.land/x/argon2@v0.9.2/lib/internal.ts:97:30)
make: *** [run] Error 1
```

You can reproduce the issue with the following code:
```ts
import { hash, Variant } from "https://deno.land/x/argon2@v0.9.2/lib/mod.ts";

const secretString = "some-secret";

const encoder = new TextEncoder();

const secret = encoder.encode(secretString);

const passwordHash = await hash("password", {
  variant: Variant.Argon2id,
  secret,
});

console.log(passwordHash);
```

**Comment by fdionisi** [comment]
@halvardssm [plugins are broken](https://github.com/denoland/deno/issues/10323) right now on Deno v1.9.x - waiting for 1.10.0 to be released.

**Comment by halvardssm** [comment]
Ah, I must have missed that notice... thanks for your quick answer!

**Comment by halvardssm** [comment]
Not sure if related, but with deno 1.10.1, I now get the error:

```shell
error: Uncaught (in promise) Error: Could not obtain symbol from the library: dlsym(0x7fb9a546f230, init): symbol not found
  return Deno.openPlugin(localPath);
              ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at Object.openPlugin (deno:runtime/js/40_plugins.js:8:22)
    at prepare (https://deno.land/x/plugin_prepare@v0.8.0/mod.ts:69:15)
```

**Comment by fdionisi** [comment]
Hey @halvardssm. The error you are seeing is because at the moment the library cannot work with the new Deno `Extension` paradigm.

I was working yesterday to upgrade the library to Deno 1.10, but I encountered some problems (progress on https://github.com/fdionisi/deno-argon2/tree/feature/upgrade-to-deno-1.10 branch).

The new Deno `Extension` mechanism makes it more clean and easy to integrate native modules, but when I try to run the new implementation, I get a segmentation error:

```
❯ deno test -A --unstable tests/lib.test.ts
Check file:///Users/federico/Code/github/deno-argon2/tests/lib.test.ts
    Finished dev [unoptimized + debuginfo] target(s) in 0.54s
[1]    86968 segmentation fault  deno test -A --unstable tests/lib.test.ts
```

After some digging and try-outs, I noticed that simply copying Deno's own [test_plugin](https://github.com/denoland/deno/tree/main/test_plugin), updating Cargo dependencies to use `deno_core = 0.87.0` and finally testing it, will result in the same segmentation error. 

I was preparing a repository to report the bug when I stumble upon a [comment](https://github.com/denoland/deno/issues/10534#issuecomment-840248579) on Deno issues that describe the exact problem (and journey) I am experiencing. 
Unluckily I'm not so knowledgeable about what is the cause of the error, so I believe we'll have to wait a bit more and see if the maintainer can help/figure this out.

**Comment by fdionisi** [comment]
Hey @halvardssm - just wanted to give you a heads up.

Apparently, the Deno plugin story needs a complete rewrite because as it is now, in certain cases, may not work. In my case, this never works... So, I believe that for now, we'll need to wait longer to use the latest Deno version. Until there is a proper fix there is no way I can support >= 1.9.0...

Just for reference, I read [this comment](https://github.com/denoland/deno/issues/10671#issuecomment-842585976), which made me join Deno's Discord server to check out the discussion on the #dev channel.

**Comment by halvardssm** [comment]
@fdionisi Thank you for letting me know. I will keep an eye on new releases for this repo 💪🏻

**Comment by mmarkmos** [comment]
Hello 😄,
Are there any updates ? Are there any plans to use the [ffi](https://github.com/denoland/deno/pull/11152) to make this work again ? Would really love to use argon2 instead of bcrypt 👍🏻

**Comment by fdionisi** [comment]
@mmarkmos, not many plans right now. The project started as part of a POC I was working on, but it ended up not being pursued as Deno was still relatively young.

Is not on top of my priorities, but I'd be happy to review the code if you don't mind preparing a PR for **ffi**.
